% Launcher

Tablero = [EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN;
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN
           EMPTY EMPTY EMPTY EMPTY EMPTY BLACK_KNIGHT BLACK_PAWN BLACK_QUEEN];
       
       
           
           
           
    